---
apiVersion: v1
kind: Secret
metadata:
  name: example-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: Y21iOS5hZG1pbg==

---
apiVersion: v1
kind: Secret
metadata:
  name: example-puma-secret
type: Opaque
data:
  username: YXBpdXNlcg==
  password: SGl0YWNoaTE=

---
apiVersion: app.example.com/v1alpha1
kind: Server 
metadata:
  name: example-bmc-server
spec:
  online: true
  bmc:
    address: 172.25.11.134
    credentialsName: example-bmc-secret
  puma:
    address: https://172.25.21.83:8444/v8/compute
    credentialsName: example-puma-secret
  power: true
