---
apiVersion: v1
kind: Secret
metadata:
  name: example-puma-server-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: v1
kind: Secret
metadata:
  name: example-puma-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm


---
apiVersion: app.example.com/v1alpha1
kind: Server 
metadata:
  name: example-puma-server
spec:
  online: true
  bmc:
    address: 172.25.11.134
    credentialsName: example-puma-server-secret
  puma:
    address: 172.25.21.83
    credentialsName: example-puma-server-secret
