apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server-operator
  template:
    metadata:
      labels:
        name: server-operator
    spec:
      serviceAccountName: server-operator
      containers:
        - name: server-operator
          # Replace this with the built image name
          image: quay.io/vivek_basappa/server-operator
          command:
          - server-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "server-operator"
