---
apiVersion: v1
kind: Secret
metadata:
  name: example-puma-server-secret-no-username
type: Opaque
data:
  username: ""
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: v1
kind: Secret
metadata:
  name: example-bmc-server-secret-no-password
type: Opaque
data:
  username: YWRtaW4=
  password: ""

---
apiVersion: app.example.com/v1alpha1
kind: Server
metadata:
  name: example-server
spec:
  online: true
  bmc:
    address: 192.168.122.1
    credentialsName: example-bmc-server-secret-no-password
  puma:
    address: https://192.168.122.21:844/v8/compute
    credentialsName: example-puma-server-secret-no-password
