---
apiVersion: v1
kind: Secret
metadata:
  name: example-puma-server-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm

---
apiVersion: v1
kind: Secret
metadata:
  name: example-bmc-server-secret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm


---
apiVersion: app.example.com/v1alpha1
kind: Server 
metadata:
  name: example-server
spec:
  online: true
  bmc:
    address: 192.168.122.1
    credentialsName: example-bmc-server-secret
  puma:
    address: https://192.168.122.12:8444/v4/compute
    credentialsName: example-puma-server-secret
